services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: library_app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - neo4j
    volumes:
      - ./:/app

  neo4j-init:
    image: neo4j:5.26.0
    entrypoint: ["/backups/neo4j-init.sh"]
    volumes:
      - ./neo4j_data:/data
      - ./neo4j_backups:/backups
    environment:
      - NEO4J_AUTH=neo4j/password
    depends_on: []
    command: []
    restart: "no"

  neo4j:
    image: neo4j:5.26.0
    environment:
      NEO4J_PLUGINS: '["apoc-extended"]'
      NEO4J_AUTH: neo4j/password
      NEO4J_apoc_export_file_enabled: true
      NEO4J_apoc_import_file_enabled: true
      NEO4J_apoc_import_file_use__neo4j__config: true
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j_data:/data
      - ./neo4j_plugins:/plugins
      - ./neo4j_backups:/backups
    depends_on:
      neo4j-init:
        condition: service_completed_successfully
