version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: library_app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - library_network
    volumes:
      - ./:/app

  postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=library_user
      - POSTGRES_PASSWORD=library_password
      - POSTGRES_DB=library_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./sql_init:/docker-entrypoint-initdb.d
    networks:
      - library_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@library.com
      - PGADMIN_DEFAULT_PASSWORD=admin_password
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
    networks:
      - library_network
    profiles:
      - admin

networks:
  library_network:
    driver: bridge
